CREATE TABLE IF NOT EXISTS hotelchain(
Chain_Name VARCHAR(40) PRIMARY KEY,
Address_Central VARCHAR(40) NOT NULL,
Num_Hotels INT NOT NULL,
email varchar(40) NOT NULL,
Phone_Number INT NOT NULL);

CREATE TABLE IF NOT EXISTS hotel(
Hotel_ID VARCHAR(5) PRIMARY KEY,
Stars INT,
Num_Rooms INT NOT NULL,
Address VARCHAR(40) NOT NULL,
email varchar(40) NOT NULL,
Phone_Number INT NOT NULL,
Chain_Name VARCHAR(40) NOT NULL,
FOREIGN KEY (Chain_Name) REFERENCES hotelchain(Chain_Name)); 

CREATE TABLE IF NOT EXISTS employee(
Employee_ID VARCHAR(5) PRIMARY KEY,
SIN VARCHAR(9) NOT NULL,
Employee_Name VARCHAR(40) NOT NULL,
Address VARCHAR(40) NOT NULL,
Position VARCHAR(40) NOT NULL,
Manages_Hotel BOOLEAN,
Hotel_ID VARCHAR(5) NOT NULL,
FOREIGN KEY (Hotel_ID) REFERENCES hotel(Hotel_ID));

CREATE TABLE IF NOT EXISTS Room(
Room_ID VARCHAR(5) PRIMARY KEY,
Price INT NOT NULL,
Amenity VARCHAR(100),
Capacity INT NOT NULL,
Room_View VARCHAR(20),
Extra_Bed BOOLEAN,
Damage VARCHAR(100),
Hotel_ID VARCHAR(5) NOT NULL,
FOREIGN KEY (Hotel_ID)
REFERENCES hotel(Hotel_ID));

CREATE TABLE booking(
Booking_ID VARCHAR(5) PRIMARY KEY,
Check_In DATE NOT NULL,
Check_Out DATE NOT NULL,
Amount INT NOT NULL);

CREATE TABLE renting(
Renting_ID VARCHAR(5) PRIMARY KEY,
Check_In DATE NOT NULL,
Check_Out DATE NOT NULL,
Payment INT NOT NULL);

CREATE TABLE archive(
Record_ID VARCHAR(5) PRIMARY KEY,
Booking VARCHAR(100),
Renting VARCHAR(100));